import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
import "./css/animate.css"
import "./css/aos.css"
import "./css/flaticon.css"
import "./css/icomoon.css"
import "./css/ionicons.min.css"
import "./css/jquery.timepicker.css"
import "./css/bootstrap-datepicker.css"
import "./css/open-iconic-bootstrap.min.css"
import "./css/style.css"
import "./css/magnific-popup.css"
import "./css/owl.carousel.min.css"
import "./css/owl.theme.default.min.css"

import Script from "next/script";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
  
  
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      <Script src="/js/jquery.min.js" strategy="beforeInteractive" />
      <Script src="/js/jquery-migrate-3.0.1.min.js" strategy="beforeInteractive" />
      <Script src="/js/popper.min.js" strategy="beforeInteractive" />
      <Script src="/js/bootstrap.min.js" strategy="beforeInteractive" />
      <Script src="/js/jquery.easing.1.3.js" strategy="beforeInteractive" />
      <Script src="/js/jquery.waypoints.min.js" strategy="beforeInteractive" />
      <Script src="/js/jquery.stellar.min.js" strategy="beforeInteractive" />
      <Script src="/js/owl.carousel.min.js" strategy="beforeInteractive" />
      <Script src="/js/jquery.magnific-popup.min.js" strategy="beforeInteractive" />
      <Script src="/js/aos.js" strategy="beforeInteractive" />
      <Script src="/js/jquery.animateNumber.min.js" strategy="beforeInteractive" />
      <Script src="/js/bootstrap-datepicker.js" strategy="beforeInteractive" />
      <Script src="/js/jquery.timepicker.min.js" strategy="beforeInteractive" />
      <Script src="/js/scrollax.min.js" strategy="beforeInteractive" />

      {/* For Google Maps */}
      <Script
        src="https://maps.googleapis.com/maps/api/js?key=YOUR_API_KEY&sensor=false"
        strategy="afterInteractive"
      />
      {/* <Script src="https://cdn.jsdelivr.net/npm/bootstrap@3.4.1/dist/js/bootstrap.min.js" integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd" crossorigin="anonymous" /> */}
      <Script src="/js/google-map.js" strategy="afterInteractive" />
      <Script src="/js/main.js" strategy="afterInteractive" />
      </body>
    </html>
  );
}
